name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: cloning repo
      continue-on-error: true
      run: |
         sudo apt install -y expect
         expect -c " 
         spawn git clone ${{ secrets.CREDS }}
         expect \"Username\"        
         send \"${{ secrets.GHUSER }}\r\"
         expect \"Password\"        
         send \"${{ secrets.GHPASS }}\r\"
         set timeout -1
         catch wait result
         interact"
    - name: Install dependencies
      run: |
        cd TRANSLATOR-OP
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with trbot
      continue-on-error: true
      timeout-minutes: 350
      run: |
        cd TRANSLATOR-OP
        python trbot.py
    - name: Loop workflow
      continue-on-error: true
      run: |
            git config --global user.name "ProgrammingError"
            git config --global user.email "iam.pro2@outlook.com"
            git clone https://github.com/ProgrammingError/t-op-wf loop
            cd loop
            echo "1" >> loop.txt
            git add loop.txt
            git commit -m "Workflow : Loop"
            expect -c "
            spawn git push -f 
            expect \"Username\"
            send \"${{ secrets.GHUSER }}\r\"
            expect \"Password\"
            send \"${{ secrets.GHPASS }}\r\"
            expect \"main -> main\"
            set timeout -10
            interact"
